version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_for_create_card
    ports:
      - "8080:8080"  
    volumes:
      - ./src:/src
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload