version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"  
    volumes:
      - ./src/config/config.toml:/src/config/config.toml
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload